#!/usr/bin/env bash
# installs and configures nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
