#!/usr/bin/env bash
# installs and configures nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R "USER":"USER" /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo systemctl restart nginx
