#!/usr/bin/env bash
# installs and configures nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i '/server_name _;/a error_page 404 /custom_404.html;\n location = /custom_404.html {\nroot /var/www/html;\ninternal;\n}' /etc/nginx/sites-available/default

sudo service nginx restart
