#!/usr/bin/env bash
# installs and configures a HAproxy load balancer

# installs ha proxy
sudo apt-get -y  install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*

#configures ha proxy  to send traffic to 2 servers
sed -i '/errorfile 504/a listen llwydgrey' /etc/haproxy/haproxy.cfg
sed -i '/listen llwydgrey/a bind :80' /etc/haproxy/haproxy.cfg
sed -i '/bind :80/a mode http' /etc/haproxy/haproxy.cfg
sed -i '/mode http/a balance roundrobin' /etc/haproxy/haproxy.cfg
sed -i '/balance roundrobin/a server 1937-web-01 54.174.143.219:80  check' /etc/haproxy/haproxy.cfg
sed -i '/server 1937-web-01 54.174.143.219:80/a server 1937-web-02 100.25.3.122:80 check' /etc/haproxy/haproxy.cfg
sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
service haproxy start
