#!/usr/bin/env bash
# Uses ssh to connect to a server using the
# private key ~/.ssh/school with the user ubuntu
cat ~/.ssh/school.pub | ssh ubuntu@34.239.249.138 \
"mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"
